server:
  port: 8089

#是否开启 swagger-ui
swagger:
  enabled: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3000MB
      max-request-size: 3000MB

# 文件存储路径
file:
  mac:
    path: ~/file/
  linux:
    path: /home/aias/file/
  windows:
    path: D:/aias/file/
  #    path: file:/D:/aias/file/
  # 文件大小 /M
  maxSize: 3000

# Model URI
model:
  # 模型路径,注意路径最后要有分隔符
  modelPath: /Users/calvin/products/4_apps/simple_text_search/text-search/models/m3e/
  # 模型名字
  modelName: traced_m3e_base_model.pt
  # for chinese - ture, others - false
  chinese: true
  # 设置为 CPU 核心数 (Core Number)
  poolSize: 4

# Vector Engine - Milvus
search:
  host: 127.0.0.1
  port: 19530
  # https://milvus.io/cn/docs/v2.0.0/build_index.md
  # https://milvus.io/cn/docs/v2.0.0/metric.md#floating
  # For floating point vectors:
  #  IVF_FLAT
  #  IVF_SQ8
  #  IVF_PQ
  #  HNSW
  #  ANNOY
  #  RHNSW_FLAT
  #  RHNSW_PQ
  #  RHNSW_SQ
  # For binary vectors:
  #  BIN_IVF_FLAT
  indexType: IVF_FLAT
  metricType: L2

  nprobe: 256
  nlist: 16384
  dimension: 768 # dimension of each vector
  collectionName: texts #collection name
  partitionName: p1