server:
  port: 8089

#是否开启 swagger-ui
swagger:
  enabled: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3000MB
      max-request-size: 3000MB

# 文件存储路径
file:
  mac:
    path: ~/file/
  linux:
    path: /home/aias/file/
  windows:
    path: D:/aias/file/
#    path: file:/D:/aias/file/
  # 文件大小 /M
  maxSize: 3000


# Model URI
model:
  # 模型路径,注意路径最后要有分隔符
  # /Users/calvin/products/4_apps/simple_text_search/text-search/models/m100/
  # D:\\ai_projects\\products\\2_nlp_sdks\\embedding\\code2vec_sdk\\models\\
  # D:\\ai_projects\\products\\2_nlp_sdks\\embedding\\codet5p_110m_sdk\\models\\
  # D:\\ai_projects\\products\\2_nlp_sdks\\embedding\\mpnet_base_v2_sdk\\models\\
  modelPath: D:\\ai_projects\\products\\2_nlp_sdks\\embedding\\codet5p_110m_sdk\\models\\
  # 模型名字
  # all-MiniLM-L12-v2.pt
  # all-MiniLM-L6-v2.pt
  # codet5p-110m.pt
  # all-mpnet-base-v2.pt
  modelName: codet5p-110m.pt
  # 设置为 CPU 核心数 (Core Number)
  poolSize: 4
  # 最大代码字符长度
  maxLength: 1024