server:
  port: 8089

#是否开启 swagger-ui
swagger:
  enabled: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3000MB
      max-request-size: 3000MB

# 文件存储路径
file:
  mac:
    path: ~/file/
  linux:
    path: /home/aias/file/
  windows:
    path: D:/aias/file/
  #    path: file:/D:/aias/file/
  # 文件大小 /M
  maxSize: 3000

# Model URI
model:
  # 模型路径,注意路径最后要有分隔符
  # /Users/calvin/products/4_apps/simple_text_search/text-search/models/m100/
  # D:\\ai_projects\\products\\2_nlp_sdks\\embedding\\code2vec_sdk\\models\\
  # D:\\ai_projects\\products\\2_nlp_sdks\\embedding\\codet5p_110m_sdk\\models\\
  # D:\\ai_projects\\products\\2_nlp_sdks\\embedding\\mpnet_base_v2_sdk\\models\\
  vecModelPath: D:\\ai_projects\\products\\2_nlp_sdks\\embedding\\code2vec_sdk\\models\\
  # 模型名字
  # all-MiniLM-L12-v2.pt
  # all-MiniLM-L6-v2.pt
  # codet5p-110m.pt
  # all-mpnet-base-v2.pt
  vecModelName: all-MiniLM-L12-v2.pt
  # 设置为 CPU 核心数 (Core Number)
  poolSize: 4
  # 最大代码字符长度
  maxLength: 1024
  # 翻译模型路径,注意路径最后要有分隔符
  transModelPath: D:\\ai_projects\\products\\4_apps\\code_search\\code-search\\models\\opus-mt-zh-en\\

# Vector Engine - Milvus
search:
  host: 127.0.0.1
  port: 19530
  # https://milvus.io/docs
  # For floating point vectors:
  #  IVF_FLAT
  #  IVF_SQ8
  #  IVF_PQ
  #  HNSW
  # For binary vectors:
  #  BIN_IVF_FLAT
  indexType: IVF_FLAT
  #  L2 - L2-norm
  #  IP - Dot-product
  #  COSINE - Angular distance
  metricType: IP

  nprobe: 256
  nlist: 16384
  dimension: 384 # dimension of each vector
  collectionName: code_feature #collection name
  partitionName: p1