server:
  port: 8089

#是否开启 swagger-ui
swagger:
  enabled: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3000MB
      max-request-size: 3000MB

# 文件存储路径
file:
  mac:
    path: ~/file/
  linux:
    path: /home/aias/file/
  windows:
    path: D:/aias/file/
#    path: file:/D:/aias/file/
  # 文件大小 /M
  maxSize: 3000


# Model URI
model:
  # 模型路径,注意路径最后要有分隔符
  # /Users/calvin/products/4_apps/simple_text_search/text-search/models/M-BERT-Base-ViT-B/
  # /Users/calvin/products/4_apps/simple_text_search/text-search/models/m3e/
  # /Users/calvin/products/4_apps/simple_text_search/text-search/models/m100/
  modelPath: /Users/calvin/products/4_apps/simple_text_search/text-search/models/m100/
  # 模型名字
  # M-BERT-Base-ViT-B.pt
  # traced_m3e_base_model.pt
  # paraphrase-xlm-r-multilingual-v1.pt
  modelName: paraphrase-xlm-r-multilingual-v1.pt
  # Support 40 languages, for chinese - ture, others - false
  chinese: true
  # 设置为 CPU 核心数 (Core Number)
  poolSize: 4